version: '3.8'

services:
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
  aspnetcoreapp:
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DOTNET_URLS=https://+:5001
      - ConnectionStrings__DefaultConnection=User ID=appuser;Password=secret;Host=db;Port=5432;Database=shop;
      - ConnectionStrings__IdentityConnection=User ID=appuser;Password=secret;Host=db;Port=5432;Database=identity;
      - DOTNET_NUGET_SIGNATURE_VERIFICATION=false
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  postgres-data:
